server:
  port: 8082
  servlet:
    context-path: /ACAPizza

spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/acapizza
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
